# docker-compose.yml
version: '2'
services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    command: sh -c 'npm run start'
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=filberttt@hotmail.com
      - URL=trucking.fildabert.com
      - VALIDATION=http
      - PUID=1000
      - PGID=1000
